name: build-and-deploy

on:
  push:
    paths-ignore: ["*.md"]
    branches:
      - main

#   allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  unit-tests-redactor-model:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.10-slim-bullseye
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: unit tests
        run: |
          cd redactor_model/
          && poetry run poe test

  # unit-tests-redactor-service:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: python:3.11.10-slim-bullseye
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: unit tests
  #       run: |
  #         cd redactor_service/
  #         && poetry run poe test

  # lint:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: python:3.11.10-slim-bullseye
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: lint redactor_model
  #       run: |
  #         cd redactor_model/
  #         && poetry run poe lint-check
  #     - name: lint redactor_model
  #       run: |
  #         cd redactor_service/
  #         && poetry run poe lint-check

  # build:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: python:3.11.10-slim-bullseye
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: lint redactor_model
  #       run: |
  #         cd redactor_model/
  #         && poetry run poe lint-check

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build, unit-tests-redactor-model, unit-tests-redactor-service, lint]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Deploy to production
  #       run: echo "Deploying to production"
